### PR TITLE
FIX: Specify logger for warning

### LINKED ISSUE #2296: Error with 20.2.0 in singularity: AttributeError: type object 'loggers' has no attribute 'warning'
This fails with 20.2.0, but works fine with 20.1.1 (~or at least, it doesn't crash at the same point~ EDIT: 20.1.1 finished perfectly).

### What version of fMRIPrep are you using?

20.2.0

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?

Singularity

```bash
VERSION="20.2.0"; singularity build fmriprep-"$VERSION".simg docker://poldracklab/fmriprep:"$VERSION"
```

### What is the exact command-line you used?
```
singularity run -B /data:/data \
        /home/mvdoc/singularity/img/fmriprep-20.2.0.simg -v \
        --participant-label "$SUBJECT" \
        --output-spaces anat fsaverage \
        --fs-license-file /home/mvdoc/freesurfer/license.txt \
        --nthreads 8 --omp-nthreads 2 \
        -w "$WORKDIR" \
        "$DATADIR" "$DERIVDIR" participant
```

### Have you checked that your inputs are BIDS valid?

BIDS dataset is valid.

```
201005-23:19:20,86 nipype.workflow IMPORTANT:

    Running fMRIPREP version 20.2.0:
      * BIDS dataset path: /data/ucsf/test-sequences-atl/data/bids-new.
      * Participant list: ['01'].
      * Run identifier: 20201005-231828_b61e5695-5d3f-4ec6-86d4-1499c10e21d9.
      * Output spaces: anat fsaverage:den-164k.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /data/ucsf/test-sequences-atl/data/derivatives/freesurfer.
201005-23:19:21,476 nipype.workflow INFO:
         Using single-band reference file(s) sub-01_ses-01_task-rest_acq-cmrrbold2p2mmmb6_dir-AP_run-10_sbref.nii.gz.
201005-23:19:22,681 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
201005-23:19:23,3 nipype.workflow INFO:
         Using single-band reference file(s) sub-01_ses-01_task-rest_acq-cmrrboldalmsemanticvis2p2mmmb4_dir-AP_run-13_sbref.nii.gz.
201005-23:19:24,68 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
201005-23:19:24,362 nipype.workflow INFO:
         Using single-band reference file(s) sub-01_ses-01_task-rest_acq-ipat2_dir-AP_run-06_sbref.nii.gz.
201005-23:19:24,961 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 84, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 304, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 167, in init_func_preproc_wf
    config.loggers.warning(
AttributeError: type object 'loggers' has no attribute 'warning'
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?

Nope

### PR DESCRIPTION
**Pull request by mgxd**
Closes #2296

### CODE REVIEW

**Review by effigies — APPROVED** [review]
Good call. Looks like this is going to affect all multi-echo datasets, so we'll need to plan a patch release in the very short term.

**Comment by effigies** [comment]
Oh, rereading, it's just single-echo datasets with `echo-` entities. (I was wondering why ds216 wasn't hitting this.) That's a bit rarer.

Would be good to try to increase coverage for workflow building with synthetic data.
