### ISSUE TITLE
Error with 20.2.0 in singularity: AttributeError: type object 'loggers' has no attribute 'warning'

### ISSUE THREAD

**Issue by mvdoc** [nipreps/fmriprep#2296]
This fails with 20.2.0, but works fine with 20.1.1 (~or at least, it doesn't crash at the same point~ EDIT: 20.1.1 finished perfectly).

### What version of fMRIPrep are you using?

20.2.0

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?

Singularity

```bash
VERSION="20.2.0"; singularity build fmriprep-"$VERSION".simg docker://poldracklab/fmriprep:"$VERSION"
```

### What is the exact command-line you used?
```
singularity run -B /data:/data \
        /home/mvdoc/singularity/img/fmriprep-20.2.0.simg -v \
        --participant-label "$SUBJECT" \
        --output-spaces anat fsaverage \
        --fs-license-file /home/mvdoc/freesurfer/license.txt \
        --nthreads 8 --omp-nthreads 2 \
        -w "$WORKDIR" \
        "$DATADIR" "$DERIVDIR" participant
```

### Have you checked that your inputs are BIDS valid?

BIDS dataset is valid.

```
201005-23:19:20,86 nipype.workflow IMPORTANT:

    Running fMRIPREP version 20.2.0:
      * BIDS dataset path: /data/ucsf/test-sequences-atl/data/bids-new.
      * Participant list: ['01'].
      * Run identifier: 20201005-231828_b61e5695-5d3f-4ec6-86d4-1499c10e21d9.
      * Output spaces: anat fsaverage:den-164k.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /data/ucsf/test-sequences-atl/data/derivatives/freesurfer.
201005-23:19:21,476 nipype.workflow INFO:
         Using single-band reference file(s) sub-01_ses-01_task-rest_acq-cmrrbold2p2mmmb6_dir-AP_run-10_sbref.nii.gz.
201005-23:19:22,681 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
201005-23:19:23,3 nipype.workflow INFO:
         Using single-band reference file(s) sub-01_ses-01_task-rest_acq-cmrrboldalmsemanticvis2p2mmmb4_dir-AP_run-13_sbref.nii.gz.
201005-23:19:24,68 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
201005-23:19:24,362 nipype.workflow INFO:
         Using single-band reference file(s) sub-01_ses-01_task-rest_acq-ipat2_dir-AP_run-06_sbref.nii.gz.
201005-23:19:24,961 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 84, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 304, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 167, in init_func_preproc_wf
    config.loggers.warning(
AttributeError: type object 'loggers' has no attribute 'warning'
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?

Nope

**Comment by mgxd** [comment]
Thanks for the report, this is a silly typo that will be fixed in #2298 and then we'll cut a new release 👍

**Comment by mvdoc** [comment]
Sorry to bother about this, but do you guys have a planned date for a new release? I have a dataset with me-epi with both two and three echoes, and I have to use fmriprep 2.1.3 to analyze. But you guys added so many new goodies in 2.2.0 that I really want to use the new version ;) I tried pulling the unstable version but it's not synced with master.

**Comment by effigies** [comment]
You're probably looking at `poldracklab/fmriprep:unstable`. Switch to `nipreps/fmriprep:unstable`.

**Comment by mvdoc** [comment]
I did pull yesterday from `nipreps/fmriprep:unstable`, but it was pointing to a previous commit, not master. I'm trying to pull again and see if I can replicate.

**Comment by effigies** [comment]
Oh, we might need to rerun something.

**Comment by mvdoc** [comment]
OK then the docker image was pointing to master but I needed maint then ;) thanks for checking!

**Comment by effigies** [comment]
Merged into `master`, so the fix should be there. I think all additional changes in current `master` are compatible with 20.2.x, so it shouldn't be a problem to reuse working directories between this upcoming `unstable` and the 20.2.1 release.

**Comment by mvdoc** [comment]
thank you!! 🎉

**Comment by effigies** [comment]
Closing since this will be in the next release.

**Comment by soichih** [comment]
When will 20.2.1 be released to dockerhub? I don't see 20.2.1 on https://hub.docker.com/r/poldracklab/fmriprep/tags?page=1&ordering=last_updated

**Comment by effigies** [comment]
It moved to `nipreps/fmriprep`.
